<?
$PERM["bitrix"]["14"]="R";
$PERM["bonus"]["7"]="R";
$PERM["bonus"]["*"]="D";
$PERM["import"]["2"]="R";
$PERM["import"]["7"]="R";
$PERM["import"]["8"]="R";
$PERM["import"]["*"]="R";
$PERM["/"]["*"]="R";
$PERM["images"]["8"]="T_84";
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["testbx"]["*"]="D";
$PERM["gosti-na-krepezh"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
?>