<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Оформление заказа");
$APPLICATION->SetPageProperty("title", "Оформление заказа");
$APPLICATION->SetTitle("Оформление заказа");
?>
        
        <div class="content">
        <div class="container">
        
        <?
        
     /*   $APPLICATION->IncludeComponent(
            "traiv:order",
            "template2",
            array(
                "COMPONENT_TEMPLATE" => "template2",
                "USER_CONSENT" => "Y",
                "USER_CONSENT_ID" => "2",
                "USER_CONSENT_IS_CHECKED" => "Y",
                "USER_CONSENT_IS_LOADED" => "N",
                "AJAX_MODE" => "N",
                "AJAX_OPTION_JUMP" => "N",
                "AJAX_OPTION_STYLE" => "Y",
                "AJAX_OPTION_HISTORY" => "N",
                "AJAX_OPTION_ADDITIONAL" => ""
            ),
            false
            );*/
        
        if ( $USER->IsAuthorized() )
        {
            if ($USER->GetID() == '3092') {
                $APPLICATION->IncludeComponent(
	"bitrix:sale.order.ajax", 
	"order_ajax_2023", 
	array(
		"PAY_FROM_ACCOUNT" => "N",
		"COUNT_DELIVERY_TAX" => "N",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
		"ALLOW_AUTO_REGISTER" => "Y",
		"SEND_NEW_USER_NOTIFY" => "N",
		"DELIVERY_NO_AJAX" => "N",
		"TEMPLATE_LOCATION" => "popup",
		"PROP_1" => "",
		"PATH_TO_BASKET" => "/personal/cart/",
		"PATH_TO_PERSONAL" => "/personal/order/",
		"PATH_TO_PAYMENT" => "/personal/order/payment/",
		"PATH_TO_ORDER" => "/personal/order/make/",
		"SET_TITLE" => "Y",
		"SHOW_ACCOUNT_NUMBER" => "Y",
		"DELIVERY_NO_SESSION" => "Y",
		"COMPATIBLE_MODE" => "N",
		"BASKET_POSITION" => "before",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"SERVICES_IMAGES_SCALING" => "adaptive",
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "2",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "Y",
		"COMPONENT_TEMPLATE" => "order_ajax_2022",
		"ALLOW_APPEND_ORDER" => "Y",
		"SHOW_NOT_CALCULATED_DELIVERIES" => "N",
		"SPOT_LOCATION_BY_GEOIP" => "Y",
		"DELIVERY_TO_PAYSYSTEM" => "d2p",
		"SHOW_VAT_PRICE" => "N",
		"USE_PREPAYMENT" => "N",
		"USE_PRELOAD" => "Y",
		"ALLOW_USER_PROFILES" => "N",
		"ALLOW_NEW_PROFILE" => "N",
		"TEMPLATE_THEME" => "blue",
		"SHOW_ORDER_BUTTON" => "final_step",
		"SHOW_TOTAL_ORDER_BUTTON" => "Y",
		"SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
		"SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
		"SHOW_DELIVERY_LIST_NAMES" => "Y",
		"SHOW_DELIVERY_INFO_NAME" => "Y",
		"SHOW_DELIVERY_PARENT_NAMES" => "Y",
		"SHOW_STORES_IMAGES" => "Y",
		"SKIP_USELESS_BLOCK" => "Y",
		"SHOW_BASKET_HEADERS" => "Y",
		"DELIVERY_FADE_EXTRA_SERVICES" => "N",
		"SHOW_NEAREST_PICKUP" => "Y",
		"DELIVERIES_PER_PAGE" => "15",
		"PAY_SYSTEMS_PER_PAGE" => "9",
		"PICKUPS_PER_PAGE" => "5",
		"SHOW_PICKUP_MAP" => "N",
		"SHOW_MAP_IN_PROPS" => "N",
		"PICKUP_MAP_TYPE" => "yandex",
		"SHOW_COUPONS" => "N",
		"SHOW_COUPONS_BASKET" => "Y",
		"SHOW_COUPONS_DELIVERY" => "Y",
		"SHOW_COUPONS_PAY_SYSTEM" => "Y",
		"PROPS_FADE_LIST_1" => array(
		),
		"PROPS_FADE_LIST_2" => array(
		),
		"ACTION_VARIABLE" => "soa-action",
		"PATH_TO_AUTH" => "/auth/",
		"DISABLE_BASKET_REDIRECT" => "N",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"USE_PHONE_NORMALIZATION" => "Y",
		"PRODUCT_COLUMNS_VISIBLE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "PROPS",
			2 => "PROPERTY_CML2_ARTICLE",
		),
		"ADDITIONAL_PICT_PROP_18" => "-",
		"ADDITIONAL_PICT_PROP_19" => "-",
		"ADDITIONAL_PICT_PROP_32" => "-",
		"PRODUCT_COLUMNS_HIDDEN" => array(
		),
		"HIDE_ORDER_DESCRIPTION" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"USE_YM_GOALS" => "Y",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_CUSTOM_MAIN_MESSAGES" => "N",
		"USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
		"USE_CUSTOM_ERROR_MESSAGES" => "N",
		"YM_GOALS_COUNTER" => "18248638",
		"YM_GOALS_INITIALIZE" => "BX-order-init",
		"YM_GOALS_EDIT_REGION" => "BX-region-edit",
		"YM_GOALS_EDIT_DELIVERY" => "BX-delivery-edit",
		"YM_GOALS_EDIT_PICKUP" => "BX-pickUp-edit",
		"YM_GOALS_EDIT_PAY_SYSTEM" => "BX-paySystem-edit",
		"YM_GOALS_EDIT_PROPERTIES" => "BX-properties-edit",
		"YM_GOALS_EDIT_BASKET" => "BX-basket-edit",
		"YM_GOALS_NEXT_REGION" => "BX-region-next",
		"YM_GOALS_NEXT_DELIVERY" => "BX-delivery-next",
		"YM_GOALS_NEXT_PICKUP" => "BX-pickUp-next",
		"YM_GOALS_NEXT_PAY_SYSTEM" => "BX-paySystem-next",
		"YM_GOALS_NEXT_PROPERTIES" => "BX-properties-next",
		"YM_GOALS_NEXT_BASKET" => "BX-basket-next",
		"YM_GOALS_SAVE_ORDER" => "buy_order"
	),
	false
);
            }
            else {
                $APPLICATION->IncludeComponent(
                    "bitrix:sale.order.ajax",
                    "order_ajax_2023",
                    array(
                        "PAY_FROM_ACCOUNT" => "N",
                        "COUNT_DELIVERY_TAX" => "N",
                        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
                        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
                        "ALLOW_AUTO_REGISTER" => "Y",
                        "SEND_NEW_USER_NOTIFY" => "N",
                        "DELIVERY_NO_AJAX" => "N",
                        "TEMPLATE_LOCATION" => "popup",
                        "PROP_1" => "",
                        "PATH_TO_BASKET" => "/personal/cart/",
                        "PATH_TO_PERSONAL" => "/personal/order/",
                        "PATH_TO_PAYMENT" => "/personal/order/payment/",
                        "PATH_TO_ORDER" => "/personal/order/make/",
                        "SET_TITLE" => "Y",
                        "SHOW_ACCOUNT_NUMBER" => "Y",
                        "DELIVERY_NO_SESSION" => "Y",
                        "COMPATIBLE_MODE" => "N",
                        "BASKET_POSITION" => "before",
                        "BASKET_IMAGES_SCALING" => "adaptive",
                        "SERVICES_IMAGES_SCALING" => "adaptive",
                        "USER_CONSENT" => "Y",
                        "USER_CONSENT_ID" => "2",
                        "USER_CONSENT_IS_CHECKED" => "Y",
                        "USER_CONSENT_IS_LOADED" => "Y",
                        "COMPONENT_TEMPLATE" => "order_ajax_2021",
                        "ALLOW_APPEND_ORDER" => "Y",
                        "SHOW_NOT_CALCULATED_DELIVERIES" => "N",
                        "SPOT_LOCATION_BY_GEOIP" => "Y",
                        "DELIVERY_TO_PAYSYSTEM" => "d2p",
                        "SHOW_VAT_PRICE" => "N",
                        "USE_PREPAYMENT" => "N",
                        "USE_PRELOAD" => "Y",
                        "ALLOW_USER_PROFILES" => "N",
                        "ALLOW_NEW_PROFILE" => "N",
                        "TEMPLATE_THEME" => "blue",
                        "SHOW_ORDER_BUTTON" => "final_step",
                        "SHOW_TOTAL_ORDER_BUTTON" => "Y",
                        "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
                        "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
                        "SHOW_DELIVERY_LIST_NAMES" => "Y",
                        "SHOW_DELIVERY_INFO_NAME" => "Y",
                        "SHOW_DELIVERY_PARENT_NAMES" => "Y",
                        "SHOW_STORES_IMAGES" => "Y",
                        "SKIP_USELESS_BLOCK" => "Y",
                        "SHOW_BASKET_HEADERS" => "Y",
                        "DELIVERY_FADE_EXTRA_SERVICES" => "N",
                        "SHOW_NEAREST_PICKUP" => "Y",
                        "DELIVERIES_PER_PAGE" => "15",
                        "PAY_SYSTEMS_PER_PAGE" => "9",
                        "PICKUPS_PER_PAGE" => "5",
                        "SHOW_PICKUP_MAP" => "N",
                        "SHOW_MAP_IN_PROPS" => "N",
                        "PICKUP_MAP_TYPE" => "yandex",
                        "SHOW_COUPONS" => "N",
                        "SHOW_COUPONS_BASKET" => "Y",
                        "SHOW_COUPONS_DELIVERY" => "Y",
                        "SHOW_COUPONS_PAY_SYSTEM" => "Y",
                        "PROPS_FADE_LIST_1" => array(
                        ),
                        "PROPS_FADE_LIST_2" => array(
                        ),
                        "ACTION_VARIABLE" => "soa-action",
                        "PATH_TO_AUTH" => "/auth/",
                        "DISABLE_BASKET_REDIRECT" => "N",
                        "EMPTY_BASKET_HINT_PATH" => "/",
                        "USE_PHONE_NORMALIZATION" => "Y",
                        "PRODUCT_COLUMNS_VISIBLE" => array(
                            0 => "PREVIEW_PICTURE",
                            1 => "PROPS",
                            2 => "PROPERTY_CML2_ARTICLE",
                        ),
                        "ADDITIONAL_PICT_PROP_18" => "-",
                        "ADDITIONAL_PICT_PROP_19" => "-",
                        "ADDITIONAL_PICT_PROP_32" => "-",
                        "PRODUCT_COLUMNS_HIDDEN" => array(
                        ),
                        "HIDE_ORDER_DESCRIPTION" => "N",
                        "COMPOSITE_FRAME_MODE" => "A",
                        "COMPOSITE_FRAME_TYPE" => "AUTO",
                        "USE_YM_GOALS" => "Y",
                        "USE_ENHANCED_ECOMMERCE" => "N",
                        "USE_CUSTOM_MAIN_MESSAGES" => "N",
                        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
                        "USE_CUSTOM_ERROR_MESSAGES" => "N",
                        "YM_GOALS_COUNTER" => "18248638",
                        "YM_GOALS_INITIALIZE" => "BX-order-init",
                        "YM_GOALS_EDIT_REGION" => "BX-region-edit",
                        "YM_GOALS_EDIT_DELIVERY" => "BX-delivery-edit",
                        "YM_GOALS_EDIT_PICKUP" => "BX-pickUp-edit",
                        "YM_GOALS_EDIT_PAY_SYSTEM" => "BX-paySystem-edit",
                        "YM_GOALS_EDIT_PROPERTIES" => "BX-properties-edit",
                        "YM_GOALS_EDIT_BASKET" => "BX-basket-edit",
                        "YM_GOALS_NEXT_REGION" => "BX-region-next",
                        "YM_GOALS_NEXT_DELIVERY" => "BX-delivery-next",
                        "YM_GOALS_NEXT_PICKUP" => "BX-pickUp-next",
                        "YM_GOALS_NEXT_PAY_SYSTEM" => "BX-paySystem-next",
                        "YM_GOALS_NEXT_PROPERTIES" => "BX-properties-next",
                        "YM_GOALS_NEXT_BASKET" => "BX-basket-next",
                        "YM_GOALS_SAVE_ORDER" => "buy_order"
                    ),
                    false
                    );
            }
        }
        else
        {
            $APPLICATION->IncludeComponent(
                "bitrix:sale.order.ajax",
                "order_ajax_2023",
                array(
                    "PAY_FROM_ACCOUNT" => "N",
                    "COUNT_DELIVERY_TAX" => "N",
                    "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
                    "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
                    "ALLOW_AUTO_REGISTER" => "Y",
                    "SEND_NEW_USER_NOTIFY" => "N",
                    "DELIVERY_NO_AJAX" => "N",
                    "TEMPLATE_LOCATION" => "popup",
                    "PROP_1" => "",
                    "PATH_TO_BASKET" => "/personal/cart/",
                    "PATH_TO_PERSONAL" => "/personal/order/",
                    "PATH_TO_PAYMENT" => "/personal/order/payment/",
                    "PATH_TO_ORDER" => "/personal/order/make/",
                    "SET_TITLE" => "Y",
                    "SHOW_ACCOUNT_NUMBER" => "Y",
                    "DELIVERY_NO_SESSION" => "Y",
                    "COMPATIBLE_MODE" => "N",
                    "BASKET_POSITION" => "before",
                    "BASKET_IMAGES_SCALING" => "adaptive",
                    "SERVICES_IMAGES_SCALING" => "adaptive",
                    "USER_CONSENT" => "Y",
                    "USER_CONSENT_ID" => "2",
                    "USER_CONSENT_IS_CHECKED" => "Y",
                    "USER_CONSENT_IS_LOADED" => "Y",
                    "COMPONENT_TEMPLATE" => "order_ajax_2021",
                    "ALLOW_APPEND_ORDER" => "Y",
                    "SHOW_NOT_CALCULATED_DELIVERIES" => "N",
                    "SPOT_LOCATION_BY_GEOIP" => "Y",
                    "DELIVERY_TO_PAYSYSTEM" => "d2p",
                    "SHOW_VAT_PRICE" => "N",
                    "USE_PREPAYMENT" => "N",
                    "USE_PRELOAD" => "Y",
                    "ALLOW_USER_PROFILES" => "N",
                    "ALLOW_NEW_PROFILE" => "N",
                    "TEMPLATE_THEME" => "blue",
                    "SHOW_ORDER_BUTTON" => "final_step",
                    "SHOW_TOTAL_ORDER_BUTTON" => "Y",
                    "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
                    "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
                    "SHOW_DELIVERY_LIST_NAMES" => "Y",
                    "SHOW_DELIVERY_INFO_NAME" => "Y",
                    "SHOW_DELIVERY_PARENT_NAMES" => "Y",
                    "SHOW_STORES_IMAGES" => "Y",
                    "SKIP_USELESS_BLOCK" => "Y",
                    "SHOW_BASKET_HEADERS" => "Y",
                    "DELIVERY_FADE_EXTRA_SERVICES" => "N",
                    "SHOW_NEAREST_PICKUP" => "Y",
                    "DELIVERIES_PER_PAGE" => "15",
                    "PAY_SYSTEMS_PER_PAGE" => "9",
                    "PICKUPS_PER_PAGE" => "5",
                    "SHOW_PICKUP_MAP" => "N",
                    "SHOW_MAP_IN_PROPS" => "N",
                    "PICKUP_MAP_TYPE" => "yandex",
                    "SHOW_COUPONS" => "N",
                    "SHOW_COUPONS_BASKET" => "Y",
                    "SHOW_COUPONS_DELIVERY" => "Y",
                    "SHOW_COUPONS_PAY_SYSTEM" => "Y",
                    "PROPS_FADE_LIST_1" => array(
                    ),
                    "PROPS_FADE_LIST_2" => array(
                    ),
                    "ACTION_VARIABLE" => "soa-action",
                    "PATH_TO_AUTH" => "/auth/",
                    "DISABLE_BASKET_REDIRECT" => "N",
                    "EMPTY_BASKET_HINT_PATH" => "/",
                    "USE_PHONE_NORMALIZATION" => "Y",
                    "PRODUCT_COLUMNS_VISIBLE" => array(
                        0 => "PREVIEW_PICTURE",
                        1 => "PROPS",
                        2 => "PROPERTY_CML2_ARTICLE",
                    ),
                    "ADDITIONAL_PICT_PROP_18" => "-",
                    "ADDITIONAL_PICT_PROP_19" => "-",
                    "ADDITIONAL_PICT_PROP_32" => "-",
                    "PRODUCT_COLUMNS_HIDDEN" => array(
                    ),
                    "HIDE_ORDER_DESCRIPTION" => "N",
                    "COMPOSITE_FRAME_MODE" => "A",
                    "COMPOSITE_FRAME_TYPE" => "AUTO",
                    "USE_YM_GOALS" => "Y",
                    "USE_ENHANCED_ECOMMERCE" => "N",
                    "USE_CUSTOM_MAIN_MESSAGES" => "N",
                    "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
                    "USE_CUSTOM_ERROR_MESSAGES" => "N",
                    "YM_GOALS_COUNTER" => "18248638",
                    "YM_GOALS_INITIALIZE" => "BX-order-init",
                    "YM_GOALS_EDIT_REGION" => "BX-region-edit",
                    "YM_GOALS_EDIT_DELIVERY" => "BX-delivery-edit",
                    "YM_GOALS_EDIT_PICKUP" => "BX-pickUp-edit",
                    "YM_GOALS_EDIT_PAY_SYSTEM" => "BX-paySystem-edit",
                    "YM_GOALS_EDIT_PROPERTIES" => "BX-properties-edit",
                    "YM_GOALS_EDIT_BASKET" => "BX-basket-edit",
                    "YM_GOALS_NEXT_REGION" => "BX-region-next",
                    "YM_GOALS_NEXT_DELIVERY" => "BX-delivery-next",
                    "YM_GOALS_NEXT_PICKUP" => "BX-pickUp-next",
                    "YM_GOALS_NEXT_PAY_SYSTEM" => "BX-paySystem-next",
                    "YM_GOALS_NEXT_PROPERTIES" => "BX-properties-next",
                    "YM_GOALS_NEXT_BASKET" => "BX-basket-next",
                    "YM_GOALS_SAVE_ORDER" => "buy_order"
                ),
                false
                );
        }
        
       
        ?></div>
        </div>

<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");
?>
